title: Emory Class of 2019
author: Swetha Rajagopalan
email: hema1996@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  # Here is a list of courses I am taking this 
  ## Fall, 2018.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
